(cl:defpackage demo_package-srv
  (:use )
  (:export
   "MAGNITUDECALCULATION"
   "<MAGNITUDECALCULATION-REQUEST>"
   "MAGNITUDECALCULATION-REQUEST"
   "<MAGNITUDECALCULATION-RESPONSE>"
   "MAGNITUDECALCULATION-RESPONSE"
  ))

