// Generated by gencpp from file demo_package/MagnitudeCalculationResponse.msg
// DO NOT EDIT!


#ifndef DEMO_PACKAGE_MESSAGE_MAGNITUDECALCULATIONRESPONSE_H
#define DEMO_PACKAGE_MESSAGE_MAGNITUDECALCULATIONRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace demo_package
{
template <class ContainerAllocator>
struct MagnitudeCalculationResponse_
{
  typedef MagnitudeCalculationResponse_<ContainerAllocator> Type;

  MagnitudeCalculationResponse_()
    : magnitude(0.0)  {
    }
  MagnitudeCalculationResponse_(const ContainerAllocator& _alloc)
    : magnitude(0.0)  {
  (void)_alloc;
    }



   typedef double _magnitude_type;
  _magnitude_type magnitude;





  typedef boost::shared_ptr< ::demo_package::MagnitudeCalculationResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::demo_package::MagnitudeCalculationResponse_<ContainerAllocator> const> ConstPtr;

}; // struct MagnitudeCalculationResponse_

typedef ::demo_package::MagnitudeCalculationResponse_<std::allocator<void> > MagnitudeCalculationResponse;

typedef boost::shared_ptr< ::demo_package::MagnitudeCalculationResponse > MagnitudeCalculationResponsePtr;
typedef boost::shared_ptr< ::demo_package::MagnitudeCalculationResponse const> MagnitudeCalculationResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::demo_package::MagnitudeCalculationResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::demo_package::MagnitudeCalculationResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::demo_package::MagnitudeCalculationResponse_<ContainerAllocator1> & lhs, const ::demo_package::MagnitudeCalculationResponse_<ContainerAllocator2> & rhs)
{
  return lhs.magnitude == rhs.magnitude;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::demo_package::MagnitudeCalculationResponse_<ContainerAllocator1> & lhs, const ::demo_package::MagnitudeCalculationResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace demo_package

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::demo_package::MagnitudeCalculationResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::demo_package::MagnitudeCalculationResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::demo_package::MagnitudeCalculationResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::demo_package::MagnitudeCalculationResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::demo_package::MagnitudeCalculationResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::demo_package::MagnitudeCalculationResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::demo_package::MagnitudeCalculationResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f3a902f9783110e2b8fe7c475e26788e";
  }

  static const char* value(const ::demo_package::MagnitudeCalculationResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf3a902f9783110e2ULL;
  static const uint64_t static_value2 = 0xb8fe7c475e26788eULL;
};

template<class ContainerAllocator>
struct DataType< ::demo_package::MagnitudeCalculationResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "demo_package/MagnitudeCalculationResponse";
  }

  static const char* value(const ::demo_package::MagnitudeCalculationResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::demo_package::MagnitudeCalculationResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 magnitude\n"
;
  }

  static const char* value(const ::demo_package::MagnitudeCalculationResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::demo_package::MagnitudeCalculationResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.magnitude);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MagnitudeCalculationResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::demo_package::MagnitudeCalculationResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::demo_package::MagnitudeCalculationResponse_<ContainerAllocator>& v)
  {
    s << indent << "magnitude: ";
    Printer<double>::stream(s, indent + "  ", v.magnitude);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DEMO_PACKAGE_MESSAGE_MAGNITUDECALCULATIONRESPONSE_H
