// Generated by gencpp from file demo_package/MagnitudeCalculation.msg
// DO NOT EDIT!


#ifndef DEMO_PACKAGE_MESSAGE_MAGNITUDECALCULATION_H
#define DEMO_PACKAGE_MESSAGE_MAGNITUDECALCULATION_H

#include <ros/service_traits.h>


#include <demo_package/MagnitudeCalculationRequest.h>
#include <demo_package/MagnitudeCalculationResponse.h>


namespace demo_package
{

struct MagnitudeCalculation
{

typedef MagnitudeCalculationRequest Request;
typedef MagnitudeCalculationResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MagnitudeCalculation
} // namespace demo_package


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::demo_package::MagnitudeCalculation > {
  static const char* value()
  {
    return "55d1a215f43fd1f64eb105a505b172c4";
  }

  static const char* value(const ::demo_package::MagnitudeCalculation&) { return value(); }
};

template<>
struct DataType< ::demo_package::MagnitudeCalculation > {
  static const char* value()
  {
    return "demo_package/MagnitudeCalculation";
  }

  static const char* value(const ::demo_package::MagnitudeCalculation&) { return value(); }
};


// service_traits::MD5Sum< ::demo_package::MagnitudeCalculationRequest> should match
// service_traits::MD5Sum< ::demo_package::MagnitudeCalculation >
template<>
struct MD5Sum< ::demo_package::MagnitudeCalculationRequest>
{
  static const char* value()
  {
    return MD5Sum< ::demo_package::MagnitudeCalculation >::value();
  }
  static const char* value(const ::demo_package::MagnitudeCalculationRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::demo_package::MagnitudeCalculationRequest> should match
// service_traits::DataType< ::demo_package::MagnitudeCalculation >
template<>
struct DataType< ::demo_package::MagnitudeCalculationRequest>
{
  static const char* value()
  {
    return DataType< ::demo_package::MagnitudeCalculation >::value();
  }
  static const char* value(const ::demo_package::MagnitudeCalculationRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::demo_package::MagnitudeCalculationResponse> should match
// service_traits::MD5Sum< ::demo_package::MagnitudeCalculation >
template<>
struct MD5Sum< ::demo_package::MagnitudeCalculationResponse>
{
  static const char* value()
  {
    return MD5Sum< ::demo_package::MagnitudeCalculation >::value();
  }
  static const char* value(const ::demo_package::MagnitudeCalculationResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::demo_package::MagnitudeCalculationResponse> should match
// service_traits::DataType< ::demo_package::MagnitudeCalculation >
template<>
struct DataType< ::demo_package::MagnitudeCalculationResponse>
{
  static const char* value()
  {
    return DataType< ::demo_package::MagnitudeCalculation >::value();
  }
  static const char* value(const ::demo_package::MagnitudeCalculationResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DEMO_PACKAGE_MESSAGE_MAGNITUDECALCULATION_H
